# Generated by Django 4.2.11 on 2024-04-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge_no", models.CharField(default=None, max_length=6)),
                ("employee_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, default=None)),
                (
                    "photo",
                    models.ImageField(blank=True, default=None, upload_to="photo/"),
                ),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MasterBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge_no", models.CharField(max_length=6)),
                ("reserved", models.BooleanField(default=False)),
            ],
        ),
    ]
