# Generated by Django 4.2.11 on 2024-05-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="masterbadge",
            name="badge_no",
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
